// AUTO-GENERATED by scripts/calibrateSlots.mjs — do not edit by hand.
// Per-template payout scalar that locks realized RTP to each template's
// rtpTarget. Regenerate after changing symbol weights/payouts or evaluation.

export const SLOT_RTP_SCALARS = {
    "vault-rush": 0.15816,
    "river-catcher": 0.776839,
    "dust-rail": 0.133199,
    "storm-banner": 0.0119814,
    "bassline-bonus": 0.00032779,
    "scarab-spin": 0.296737,
    "bars": 51.9457,
    "blue-samurai": 2.21304,
    "wanted-revelation": 1.41364,
    "gates-ascent": 0.36584,
    "bass-bayou": 0.170582,
    "mummy-cascade": 0.000319001,
    "phoenix-megaways": 0.0207994,
    "mansion-megaways": 0.038992,
    "ghostblade-strike": 0.371687,
    "iron-fist": 0.304687,
    "coop-cluck": 0.0520109,
    "miko-spirit": 0.0536472,
    "forge-anvil": 2.18478,
    "gummy-drops": 0.000018251
}
