// AUTO-GENERATED by scripts/calibrateSlots.mjs — do not edit by hand.
// Per-template payout scalar that locks realized RTP to each template's
// rtpTarget. Regenerate after changing symbol weights/payouts or evaluation.

export const SLOT_RTP_SCALARS = {
    "vault-rush": 0.25031,
    "river-catcher": 0.96364,
    "dust-rail": 0.84685,
    "storm-banner": 0.12733,
    "bassline-bonus": 0.00156,
    "scarab-spin": 0.4025,
    "bars": 58.76794,
    "blue-samurai": 2.5169,
    "wanted-revelation": 1.42151,
    "gates-ascent": 0.41821,
    "bass-bayou": 0.17158,
    "mummy-cascade": 0.00032,
    "phoenix-megaways": 0.62607,
    "mansion-megaways": 0.61916,
    "ghostblade-strike": 0.56844,
    "iron-fist": 0.29009,
    "coop-cluck": 0.08926,
    "miko-spirit": 0.08206,
    "forge-anvil": 2.19184,
    "gummy-drops": 0.00014
}
