#!/usr/bin/env node
import { mkdir, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const API_URL = 'https://geraldburke.com/apis/plateautarot/?count=78&seed=0'
const OUT_DIR = join(ROOT, 'public', 'assets', 'tarot', 'plateau')
const PUBLIC_JSON = join(ROOT, 'public', 'data', 'tarot-deck.json')
const SRC_MODULE = join(ROOT, 'src', 'data', 'tarotDeck.generated.js')
const BACK_IMAGE = '/assets/tarot/monochrome/back.png'

function slugify(value) {
    return String(value || '')
        .toLowerCase()
        .normalize('NFKD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
}

async function fetchJson(url) {
    const res = await fetch(url)
    if (!res.ok) throw new Error(`failed to fetch ${url}: ${res.status}`)
    return res.json()
}

async function fetchBuffer(url) {
    const res = await fetch(url)
    if (!res.ok) throw new Error(`failed to fetch ${url}: ${res.status}`)
    return Buffer.from(await res.arrayBuffer())
}

function normalizeCard(card) {
    const numericId = Number(card.id)
    const filename = `${String(numericId).padStart(2, '0')}-${slugify(card.name)}.jpg`
    const arcana = String(card.arcana || '').toLowerCase() === 'major' ? 'major' : 'minor'
    const suit = arcana === 'major' ? 'major' : String(card.suit || '').toLowerCase()
    const rank = String(card.rank || '')
    return {
        id: `plateau-${String(numericId).padStart(2, '0')}`,
        sourceId: numericId,
        name: card.name,
        arcana,
        suit,
        rank,
        symbols: card.symbols || '',
        description: card.description || '',
        image: `/assets/tarot/plateau/${filename}`,
        backImage: BACK_IMAGE,
        sourceImageURL: card.imageURL,
    }
}

async function main() {
    await mkdir(OUT_DIR, { recursive: true })
    await mkdir(dirname(PUBLIC_JSON), { recursive: true })
    await mkdir(dirname(SRC_MODULE), { recursive: true })

    const payload = await fetchJson(API_URL)
    const cards = [...(payload.cards || [])]
        .filter(card => card && card.id && card.imageURL)
        .sort((a, b) => Number(a.id) - Number(b.id))
        .map(normalizeCard)

    if (cards.length !== 78) {
        throw new Error(`expected 78 Plateau Tarot cards, received ${cards.length}`)
    }

    for (const card of cards) {
        const file = join(ROOT, 'public', card.image)
        if (existsSync(file)) continue
        const url = new URL(card.sourceImageURL).href
        const buffer = await fetchBuffer(url)
        await writeFile(file, buffer)
    }

    const json = {
        source: {
            name: 'Plateau Tarot API',
            api: API_URL,
            repository: 'https://github.com/geraldfingburke/plateau-tarot-api',
            license: 'Unlicense / public domain-style per repository README',
        },
        generatedAt: new Date().toISOString(),
        cardBack: BACK_IMAGE,
        cards,
    }

    await writeFile(PUBLIC_JSON, `${JSON.stringify(json, null, 2)}\n`)
    await writeFile(
        SRC_MODULE,
        [
            '// Generated by scripts/fetchPlateauTarot.mjs.',
            '// Source: Plateau Tarot API, Unlicense / public domain-style README.',
            `export const TAROT_DECK_SOURCE = ${JSON.stringify(json.source, null, 4)}`,
            `export const TAROT_CARD_BACK = ${JSON.stringify(BACK_IMAGE)}`,
            `export const TAROT_DECK = ${JSON.stringify(cards, null, 4)}`,
            '',
        ].join('\n'),
    )

    // eslint-disable-next-line no-console
    console.log(`[tarot] wrote ${cards.length} cards to ${PUBLIC_JSON}`)
}

main().catch(err => {
    // eslint-disable-next-line no-console
    console.error(err)
    process.exit(1)
})
